spring: 
  profiles:
    active: '@activatedProperties@'
  banner:
    location: classpath:/banners/banner-dev.txt  
  main:
    allow-bean-definition-overriding: true
  boot: 
    admin:
      context-path: /admin  #A different context path for Spring boot admin server has been provided avoiding conflict with eureka       instance-proxy:
        ignored-headers: Authorization, Cookie, Set-Cookie      monitor:        status-interval: 300000 # 5 minutos        status-lifetime: 300000 # 5 minutos
  datasource: # CONFIGURACIONES DE CONEXION
    url: jdbc:mysql://localhost/stegeriluminacion?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=America/Mexico_City
    username: root
    password: G1lb3rt0.
    driver-class-name: com.mysql.jdbc.Driver 
    continue-on-error: true 
    hikari:
      connection-timeout: 20000 #(20 segundos) maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 15 #maximum pool size
      idle-timeout: 10000 #(10 segundos)maximum idle time for connection
      max-lifetime: 1000 #(1 segundo) maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:  ## DIRECTIVA Y CONFIGURACIONES DEL FRAMEWORK JPA
    show-sql : true # Muestra o pinta lo que hace pda los queryes
    database: mysql # lenguaje de los querys es mysql
    hibernate:  
      ddl-auto: update # quieres actualizar la tabla cada vezx que se conecte
    properties:
      hibernate:
        format_sql: true # le da formato a los query
        dialect: org.hibernate.dialect.MySQL57Dialect
    database-platform: org.hibernate.dialect.MySQL57Dialect 
    

eureka: 
  datacenter: Main
  environment: prod
  region: default
  instance:
    hostname: localhost      lease-renewal-interval-in-seconds: 300000 # 5 minutos
    lease-expiration-duration-in-seconds: 300000 # 5 minutos
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8600/discovery-server/eureka
    eureka-server-read-timeout-seconds: 180000 # 3 minutos
    eureka-server-connect-timeout-seconds: 180000 # 3 minutos    registry-fetch-interval-seconds:  300000 # 5 minutos
  # ZIPKIN
  zipkin:
    base-url: http://localhost:8609/micro-zipkin/
    enabled: true
    discovery-client-enabled: true
  # SLEUTH
  sleuth: 
    feign:
      enabled: true
    http:
      enabled: true
    zuul:
      enabled: true   
    enabled: true
    sampler:
      probability: 1

# MANAGEMENT
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  
# SECURITY
security:   
  unprotected-paths: /heartbit , /admin/instances , /eureka/, /eureka/**
  jwt: 
    resource-id: stegerilumination_resource
  oauth2:
    resource:
      user-info-uri:  http://localhost:8602/micro-auth/usuario
      preferTokenInfo: true
      
# LOGGER
logging:
  level:
    org:
      springframework:
        web: NONE
        security: NONE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: NONE # IMPRIME LOS DATOS ENTRANTES A HIBERNATE

