# APLICACION VERSION
app:
  version: 1.0.0
   
spring:
  profiles: ## SIRVEN PARA SEPARAR LAS DIREFENTES CONFIGURACIONES DEL SISTEMA
    active: '@activatedProperties@' ## NOMBRE DEL PERFIL
  banner:
    location: classpath:/banners/banner-gilberto.txt
  main:
    allow-bean-definition-overriding: true ## SOBRE ESCRIBE BEAN (OBJETOS) REPETIDOS ENTRE PROYECTO
  jackson: # JACKSON - ES USADA POR SPRING WEB, ES UNA LIBRERIA DE TRANSFORMACIÃ“N DE OBJETOS 
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Mexico_City
    joda-date-time-format: yyyy-MM-dd HH:MM:SS
    locale: es_MX 
  datasource: # CONFIGURACIONES DE CONEXION
    url: jdbc:mysql://localhost/stegeriluminacion?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=America/Mexico_City
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/datos/catalogos.sql,classpath:/datos/productos.sql
    continue-on-error: true
  jpa:  ## DIRECTIVA Y CONFIGURACIONES DEL FRAMEWORK JPA
    show-sql : true # Muestra o pinta lo que hace pda los queryes
    database: mysql # lenguaje de los querys es mysql
    hibernate:  
      ddl-auto: update # quieres actualizar la tabla cada vezx que se conecte
    properties:
      hibernate:
        format_sql: true # le da formato a los query
        dialect: org.hibernate.dialect.MySQL57Dialect
    database-platform: org.hibernate.dialect.MySQL57Dialect
  # ZIPKIN
  zipkin:
    storage:
      type: mysql
    base-url: http://localhost:8609/micro-zipkin/
    enabled: true
    discovery-client-enabled: true
  # SLEUTH
  sleuth: 
    enabled: true
    feign:
      enabled: true
    http:
      enabled: true
    zuul:
      enabled: true   
    sampler:
      probability: 1 
  # BOOT ADMIN  
  boot:
    admin:  
      client: 
        enabled: true
        url: http://localhost:8600/discovery-server/admin
        instance:
          service-base-url: http://localhost:8605
    
# EUREKA  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8600/discovery-server/eureka
      
   
# METRICAS CON PROMETHEUS Y GRAFANA
management:
  server:
    port: 8605
  endpoint:
    metrics: 
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always 
    prometheus:
      enabled: true
  endpoints:
    web: 
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true 
          

# SWAGGER
swagger:
  config:
    resource-id: stegerilumination_resource
    base-package: micro.administracion
    variables:  
      resource-owner-password-credentials-grant: http://localhost:8601/stegeriluminacion/uaa/oauth/token
      client-id: stegerilumination
      client-secret: 123
      app-name: Micro-Administracion
      scope-separator: ","
      oauth-builder: spring_oauth  
      secured-paths: /none.*


# IDIOMA 
languaje:
  config:
    validation:
      base-name: languaje/ValidationMessages
    header: Accept-Language
    base-name: languaje/messages
    encoding: ISO-8859-1
    locales: en , es


# SECURITY
security:  
  unprotected-paths: /heartbit , /producto/** , /actuator/**
  jwt: 
    resource-id: stegerilumination_resource
  oauth2:
    resource:
      user-info-uri:  http://localhost:8602/micro-auth/usuario
      preferTokenInfo: true

    
# LOGGER
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
      hibernate: 
        type: #trace
          descriptor:
            sql:
              BasicBinder: TRACE # IMPRIME LOS DATOS ENTRANTES A HIBERNATE 
       