spring:
  profiles:
    active: '@activatedProperties@'
  banner:
    location: classpath:/banners/banner-dev.txt
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Mexico_City
    joda-date-time-format: yyyy-MM-dd HH:MM:SS
    locale: es_MX
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: pruebita201910@gmail.com
    password: Prueba2019
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false
  datasource:
    url: jdbc:mysql://localhost/stegeriluminacion?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=America/Mexico_City
    username: root
    password: G1lb3rt0.
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
    hikari:
      connection-timeout: 20000 #(20 segundos) maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #(10 segundos)maximum idle time for connection
      max-lifetime: 1000 #(1 segundo) maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:
    show-sql : true
    database : mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    database-platform: org.hibernate.dialect.MySQL57Dialect
  # ZIPKIN
  zipkin:
    base-url: http://localhost:8609/micro-zipkin/
    enabled: true
    discovery-client-enabled: true
  # SLEUTH
  sleuth: 
    feign:
      enabled: true
    http:
      enabled: true
    zuul:
      enabled: true   
    enabled: true
    sampler:
      probability: 1
  # BOOT ADMIN  
  boot:
    admin:  
      client: 
        enabled: true
        url: http://localhost:8600/discovery-server/admin  
        instance:
          service-base-url: http://localhost:8603  


# EUREKA  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8600/discovery-server/eureka
      
   
# METRICAS CON PROMETHEUS Y GRAFANA
management:
  server:
    port: 8603
  endpoint:
    metrics: 
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always 
    prometheus:
      enabled: true
  endpoints:
    web: 
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true 
        
# SWAGGER
swagger:
  config:
    resource-id: stegerilumination_resource
    base-package: micro.correos
    variables:  
      resource-owner-password-credentials-grant: http://localhost:8601/stegeriluminacion/uaa/oauth/token
      client-id: stegerilumination
      client-secret: 123
      app-name: Micro-Correos
      scope-separator: ","
      oauth-builder: spring_oauth  
      secured-paths: /none.* 

# IDIOMA 
languaje:
  config:
    validation:
      base-name: languaje/ValidationMessages
    header: Accept-Language
    base-name: languaje/messages
    encoding: ISO-8859-1
    locales: en , es


# SECURITY
security:
  unprotected-paths: /heartbit/**, /correo/heartbit/** , /correo/registro/** , /correo/cambiar/password/**, /actuator/**
  jwt: 
    resource-id: stegerilumination_resource
  oauth2:
    resource:
      user-info-uri: http://localhost:8602/micro-auth/usuario
      preferTokenInfo: true
       
# LOGGER
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
      hibernate: 
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # IMPRIME LOS DATOS ENTRANTES A HIBERNATE 
      
           